name: Run Unit Tests
on:
  pull_request: 
    branches: 
      - main
    types: 
      - opened
      - edited
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  install-node-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '18.x'
          
      - name: Cache Dependencies
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm i

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Run unit tests
        run: npm run test-unit